# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.setEnabled(True)
        MainWidget.resize(960, 658)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWidget.sizePolicy().hasHeightForWidth())
        MainWidget.setSizePolicy(sizePolicy)
        MainWidget.setMouseTracking(False)
        MainWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.btnCalc = QtWidgets.QPushButton(MainWidget)
        self.btnCalc.setGeometry(QtCore.QRect(610, 250, 80, 22))
        self.btnCalc.setObjectName("btnCalc")
        self.btnChooseFile = QtWidgets.QPushButton(MainWidget)
        self.btnChooseFile.setGeometry(QtCore.QRect(520, 40, 141, 31))
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.label = QtWidgets.QLabel(MainWidget)
        self.label.setGeometry(QtCore.QRect(40, 110, 211, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWidget)
        self.label_2.setGeometry(QtCore.QRect(370, 110, 221, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWidget)
        self.label_3.setGeometry(QtCore.QRect(40, 400, 211, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(MainWidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 40, 221, 31))
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(MainWidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 150, 221, 241))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(MainWidget)
        self.listWidget_2.setGeometry(QtCore.QRect(370, 150, 221, 241))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(MainWidget)
        self.listWidget_3.setGeometry(QtCore.QRect(30, 440, 221, 141))
        self.listWidget_3.setObjectName("listWidget_3")
        self.btnAdd = QtWidgets.QPushButton(MainWidget)
        self.btnAdd.setGeometry(QtCore.QRect(270, 200, 80, 22))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRm = QtWidgets.QPushButton(MainWidget)
        self.btnRm.setGeometry(QtCore.QRect(270, 330, 80, 22))
        self.btnRm.setObjectName("btnRm")
        self.listWidget_4 = QtWidgets.QListWidget(MainWidget)
        self.listWidget_4.setGeometry(QtCore.QRect(710, 440, 221, 141))
        self.listWidget_4.setObjectName("listWidget_4")
        self.listWidget_5 = QtWidgets.QListWidget(MainWidget)
        self.listWidget_5.setGeometry(QtCore.QRect(710, 150, 221, 241))
        self.listWidget_5.setObjectName("listWidget_5")
        self.label_4 = QtWidgets.QLabel(MainWidget)
        self.label_4.setGeometry(QtCore.QRect(710, 110, 221, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(MainWidget)
        self.label_5.setGeometry(QtCore.QRect(710, 400, 221, 41))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(MainWidget)
        self.btnChooseFile.clicked.connect(MainWidget.slotChooseFile)
        self.btnCalc.clicked.connect(MainWidget.slotCalc)
        self.btnAdd.clicked.connect(MainWidget.slotAdd)
        self.btnRm.clicked.connect(MainWidget.slotRm)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Production System"))
        self.btnCalc.setText(_translate("MainWidget", "Calculate"))
        self.btnChooseFile.setText(_translate("MainWidget", "Choose Rule File"))
        self.label.setText(_translate("MainWidget", "Accepted Data"))
        self.label_2.setText(_translate("MainWidget", "Input Database"))
        self.label_3.setText(_translate("MainWidget", "Expected Result"))
        self.listWidget.setSortingEnabled(True)
        self.listWidget_3.setSortingEnabled(True)
        self.btnAdd.setText(_translate("MainWidget", "Add-->"))
        self.btnRm.setText(_translate("MainWidget", "<--Remove"))
        self.label_4.setText(_translate("MainWidget", "Output Database"))
        self.label_5.setText(_translate("MainWidget", "Result"))

